'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace IQDOC_Sanitas.ScriptGeneral
    ''' <summary>
    '''The Login recording.
    ''' </summary>
    <TestModule("2ba9adbb-a40f-4ce1-93a5-6ce1377abf3c", ModuleType.Recording, 1)> _
    Partial Public Class Login
        Implements ITestModule
    
        ''' <summary>
        ''' Holds an instance of the Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        ''' </summary>
        Public Shared repo as Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository = Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository.Instance
    
        Shared _instance as Login = new Login()
    
        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub
    
        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As Login
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
    
        ''' <summary>
        ''' Gets or sets the value of variable Compania.
        ''' </summary>
        <TestVariable("6dfb5aab-fc5e-4822-a9f1-b097fc71ce1d")> _
        Public Property Compania As String
            Get
                Return repo.Compania
            End Get
            Set(ByVal value As String)
                repo.Compania = value
            End Set
        End Property
    
        ''' <summary>
        ''' Gets or sets the value of variable Linea.
        ''' </summary>
        <TestVariable("33494307-537b-4d10-a8c0-dbb1c23a5194")> _
        Public Property Linea As String
            Get
                Return repo.Linea
            End Get
            Set(ByVal value As String)
                repo.Linea = value
            End Set
        End Property

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
            <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub
    
        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 1.00
    
            Init()
    
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.TxtLogin' at 18;12.", repo.FrmLogin.TxtLoginInfo, new RecordItemIndex(0))
            repo.FrmLogin.TxtLogin.Click("18;12")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'pruebassanitas5' with focus on 'FrmLogin.TxtLogin'.", repo.FrmLogin.TxtLoginInfo, new RecordItemIndex(1))
            repo.FrmLogin.TxtLogin.PressKeys("pruebassanitas5")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.TxtPassword' at 33;5.", repo.FrmLogin.TxtPasswordInfo, new RecordItemIndex(2))
            repo.FrmLogin.TxtPassword.Click("33;5")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test.2019' with focus on 'FrmLogin.TxtPassword'.", repo.FrmLogin.TxtPasswordInfo, new RecordItemIndex(3))
            repo.FrmLogin.TxtPassword.PressKeys("Test.2019")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.CmbCompania' at 66;16.", repo.FrmLogin.CmbCompaniaInfo, new RecordItemIndex(4))
            repo.FrmLogin.CmbCompania.Click("66;16")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.DdlCompania'.", repo.List1000.DdlCompaniaInfo, new RecordItemIndex(5))
            repo.List1000.DdlCompania.Select()
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.DdlCompania' at Center.", repo.List1000.DdlCompaniaInfo, new RecordItemIndex(6))
            repo.List1000.DdlCompania.Click()
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(7))
            Delay.Duration(4000, False)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.CmbLinea' at 47;5.", repo.FrmLogin.CmbLineaInfo, new RecordItemIndex(8))
            repo.FrmLogin.CmbLinea.Click("47;5")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.CuentasMedicas' at 36;8.", repo.List1000.CuentasMedicasInfo, new RecordItemIndex(9))
            repo.List1000.CuentasMedicas.Click("36;8")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin.CmdAceptar' at 21;9.", repo.FrmLogin.CmdAceptarInfo, new RecordItemIndex(10))
            repo.FrmLogin.CmdAceptar.Click("21;9")
            Delay.Milliseconds(0)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
