'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace IQDOC_Sanitas.CargaDatos
    ''' <summary>
    '''The AbrirVentanaInfo recording.
    ''' </summary>
    <TestModule("1fb01ab9-8d58-4c3d-8b69-ca023ca1e03d", ModuleType.Recording, 1)> _
    Partial Public Class AbrirVentanaInfo
        Implements ITestModule
    
        ''' <summary>
        ''' Holds an instance of the Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        ''' </summary>
        Public Shared repo as Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository = Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository.Instance
    
        Shared _instance as AbrirVentanaInfo = new AbrirVentanaInfo()
    
        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub
    
        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As AbrirVentanaInfo
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
            <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub
    
        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 1.00
    
            Init()
    
            'Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ''.", new RecordItemIndex(0))
            'Keyboard.Press("")
            'Delay.Milliseconds(20)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'MDIPrincipal.SomeContainer' at 549;102.", repo.MDIPrincipal.SomeContainerInfo, new RecordItemIndex(1))
            repo.MDIPrincipal.SomeContainer.Click(System.Windows.Forms.MouseButtons.Right, "549;102")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.TabMain1' at 597;-297.", repo.MDIPrincipal.TabMain1Info, new RecordItemIndex(2))
            repo.MDIPrincipal.TabMain1.Click("597;-297")
            Delay.Milliseconds(0)
            
            'Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDatosImagen.CmdCerrar' at Center.", repo.FrmDatosImagen.CmdCerrarInfo, new RecordItemIndex(3))
            'repo.FrmDatosImagen.CmdCerrar.Click()
            'Delay.Milliseconds(0)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
