'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace IQDOC_Sanitas.CargaDatos
    ''' <summary>
    '''The CargaDatos4 recording.
    ''' </summary>
    <TestModule("447d2d85-1269-425b-bf56-108d6d5926a5", ModuleType.Recording, 1)> _
    Partial Public Class CargaDatos4
        Implements ITestModule
    
        ''' <summary>
        ''' Holds an instance of the Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        ''' </summary>
        Public Shared repo as Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository = Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository.Instance
    
        Shared _instance as CargaDatos4 = new CargaDatos4()
    
        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
            ValBruto = "10000"
        End Sub
    
        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As CargaDatos4
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
    
        Dim _ValBruto As String
    
        ''' <summary>
        ''' Gets or sets the value of variable ValBruto.
        ''' </summary>
        <TestVariable("193a8434-a58d-49bc-b9fb-b3ec2b843aa3")> _
        Public Property ValBruto As String
            Get
                Return _ValBruto
            End Get
            Set(ByVal value As String)
                _ValBruto = value
            End Set
        End Property

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
            <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub
    
        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 1.00
    
            Init()
    
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.ValorBruto' at Center.", repo.MDIPrincipal.TabMain.ValorBrutoInfo, new RecordItemIndex(0))
            repo.MDIPrincipal.TabMain.ValorBruto.DoubleClick()
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValBruto' with focus on 'MDIPrincipal.TabMain.ValorBruto'.", repo.MDIPrincipal.TabMain.ValorBrutoInfo, new RecordItemIndex(1))
            repo.MDIPrincipal.TabMain.ValorBruto.PressKeys(ValBruto)
            Delay.Milliseconds(0)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
