'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace IQDOC_Sanitas.CargaDatos
    ''' <summary>
    '''The CargaDevolucion recording.
    ''' </summary>
    <TestModule("350af07b-c0bc-4558-ac35-9ca5dc87b773", ModuleType.Recording, 1)> _
    Partial Public Class CargaDevolucion
        Implements ITestModule
    
        ''' <summary>
        ''' Holds an instance of the Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        ''' </summary>
        Public Shared repo as Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository = Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository.Instance
    
        Shared _instance as CargaDevolucion = new CargaDevolucion()
    
        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub
    
        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As CargaDevolucion
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
    
        ''' <summary>
        ''' Gets or sets the value of variable CodCausal.
        ''' </summary>
        <TestVariable("76573065-3087-4296-9bf6-8692000dcf32")> _
        Public Property CodCausal As String
            Get
                Return repo.CodCausal
            End Get
            Set(ByVal value As String)
                repo.CodCausal = value
            End Set
        End Property

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
            <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub
    
        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 1.00
    
            Init()
    
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F7}' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, new RecordItemIndex(0))
            repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys("{F7}")
            Delay.Milliseconds(0)
            
            'Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'FrmControllerCapturer.CodigoCausal'.", repo.FrmControllerCapturer.CodigoCausalInfo, new RecordItemIndex(1))
            'repo.FrmControllerCapturer.CodigoCausal.Focus()
            'Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'FrmControllerCapturer.CodigoCausal'.", repo.FrmControllerCapturer.CodigoCausalInfo, new RecordItemIndex(2))
            repo.FrmControllerCapturer.CodigoCausal.PressKeys(" ")
            Delay.Milliseconds(0)
            
            'Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.CodigoCausal' at 46;8.", repo.FrmControllerCapturer.CodigoCausalInfo, new RecordItemIndex(3))
            'repo.FrmControllerCapturer.CodigoCausal.Click("46;8")
            'Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.Text' at 50;27.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(4))
            repo.FrmControllerCapturer.Text.Click("50;27")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'devoluciones Prueba' with focus on 'FrmControllerCapturer.Text'.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(5))
            repo.FrmControllerCapturer.Text.PressKeys("devoluciones Prueba")
            Delay.Milliseconds(0)
            
            'Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.Text' at 144;161.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(6))
            'repo.FrmControllerCapturer.Text.Click("144;161")
            'Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.BtnSalirCausal' at Center.", repo.FrmControllerCapturer.BtnSalirCausalInfo, new RecordItemIndex(7))
            repo.FrmControllerCapturer.BtnSalirCausal.Click()
            Delay.Milliseconds(0)
            
            'Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, new RecordItemIndex(8))
            'repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys("{Tab}")
            'Delay.Milliseconds(0)
            
            Try
                'Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, new RecordItemIndex(9))
                'repo.InformacionRIPS_cof.Aceptar.Click()
                'Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(9))
            End Try
    
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
