'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace IQDOC_Sanitas.CargaDatos
    ''' <summary>
    '''The CargaDatos2 recording.
    ''' </summary>
    <TestModule("efdb6eb4-334f-4ba0-8203-3ff7442ffb76", ModuleType.Recording, 1)> _
    Partial Public Class CargaDatos2
        Implements ITestModule
    
        ''' <summary>
        ''' Holds an instance of the Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        ''' </summary>
        Public Shared repo as Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository = Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository.Instance
    
        Shared _instance as CargaDatos2 = new CargaDatos2()
    
        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
            Periodo = "11232020"
            TipHonorario = "AB -- AMBULANCIA"
            ValBruto = "10000"
            FechaFactura = "yourtext"
        End Sub
    
        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As CargaDatos2
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
    
        Dim _Periodo As String
    
        ''' <summary>
        ''' Gets or sets the value of variable Periodo.
        ''' </summary>
        <TestVariable("58f0b3fc-0aa6-4084-ac4d-8ab0bbee953c")> _
        Public Property Periodo As String
            Get
                Return _Periodo
            End Get
            Set(ByVal value As String)
                _Periodo = value
            End Set
        End Property
    
        Dim _TipHonorario As String
    
        ''' <summary>
        ''' Gets or sets the value of variable TipHonorario.
        ''' </summary>
        <TestVariable("c9faf717-5d29-4506-9df5-5364aaca970c")> _
        Public Property TipHonorario As String
            Get
                Return _TipHonorario
            End Get
            Set(ByVal value As String)
                _TipHonorario = value
            End Set
        End Property
    
        Dim _ValBruto As String
    
        ''' <summary>
        ''' Gets or sets the value of variable ValBruto.
        ''' </summary>
        <TestVariable("cead99af-3eab-475b-97e7-d07c7a21639e")> _
        Public Property ValBruto As String
            Get
                Return _ValBruto
            End Get
            Set(ByVal value As String)
                _ValBruto = value
            End Set
        End Property
    
        Dim _FechaFactura As String
    
        ''' <summary>
        ''' Gets or sets the value of variable FechaFactura.
        ''' </summary>
        <TestVariable("8567d7f2-1d5a-45cd-822f-89131332097e")> _
        Public Property FechaFactura As String
            Get
                Return _FechaFactura
            End Get
            Set(ByVal value As String)
                _FechaFactura = value
            End Set
        End Property
    
        ''' <summary>
        ''' Gets or sets the value of variable Sucursal.
        ''' </summary>
        <TestVariable("f53dbe53-95a3-40e9-b9f5-2b741287451a")> _
        Public Property Sucursal As String
            Get
                Return repo.Sucursal
            End Get
            Set(ByVal value As String)
                repo.Sucursal = value
            End Set
        End Property

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
            <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub
    
        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 1.00
    
            Init()
    
            Try
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, new RecordItemIndex(0))
                repo.InformacionRIPS_cof.Aceptar.Click()
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(0))
            End Try
    
            'Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.CR254946CONS307CENTROMEDICOSANT'.", repo.List1000.CR254946CONS307CENTROMEDICOSANTInfo, new RecordItemIndex(1))
            'repo.List1000.CR254946CONS307CENTROMEDICOSANT.Select()
            'Delay.Milliseconds(0)
            
            'Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'MDIPrincipal.TabMain.CerrarSucursalDDL'.", repo.MDIPrincipal.TabMain.CerrarSucursalDDLInfo, new RecordItemIndex(2))
            'repo.MDIPrincipal.TabMain.CerrarSucursalDDL.Press()
            'Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.FechaFactura' at Center.", repo.MDIPrincipal.TabMain.FechaFacturaInfo, new RecordItemIndex(3))
            repo.MDIPrincipal.TabMain.FechaFactura.DoubleClick()
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaFactura' with focus on 'MDIPrincipal.TabMain.FechaFactura'.", repo.MDIPrincipal.TabMain.FechaFacturaInfo, new RecordItemIndex(4))
            repo.MDIPrincipal.TabMain.FechaFactura.PressKeys(FechaFactura)
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.TextArea2' at Center.", repo.MDIPrincipal.TabMain.TextArea2Info, new RecordItemIndex(5))
            repo.MDIPrincipal.TabMain.TextArea2.DoubleClick()
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Periodo' with focus on 'MDIPrincipal.TabMain.TextArea2'.", repo.MDIPrincipal.TabMain.TextArea2Info, new RecordItemIndex(6))
            repo.MDIPrincipal.TabMain.TextArea2.EnsureVisible()
            Keyboard.Press(Periodo)
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipHonorario' with focus on 'MDIPrincipal.TabMain.TipoHonorarioText'.", repo.MDIPrincipal.TabMain.TipoHonorarioTextInfo, new RecordItemIndex(7))
            repo.MDIPrincipal.TabMain.TipoHonorarioText.PressKeys(TipHonorario)
            Delay.Milliseconds(0)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
