'''////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' Your custom recording code should go in this file.
' The designer will only add methods to this file, so your custom code won't be overwritten.
' http://www.ranorex.com
'
'''////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Repository
Imports Ranorex.Core.Testing

Namespace IQDOC_Sanitas.CargaDatos
	Public Partial Class Clasificacion
		''' <summary>
		''' This method gets called right after the recording has been started.
		''' It can be used to execute recording specific initialization code.
		''' </summary>
		Private Sub Init()
			' Your recording specific initialization code goes here.
		End Sub

		Public Sub Clasificar()
			' TODO: Replace the following line with your code implementation.
			'   throw new NotImplementedException();

			Dim index As Integer = 0
			Dim codigo As [String] = String.Empty
			Dim rnd As New Random()


			While Not repo.MensajePantalla.FinDocumentoInfo.Exists(2000)


				Dim num As Integer = rnd.[Next](1, 44)
				'WinForms.MessageBox.Show(num.ToString());
				If index = 0 Then
					codigo = "00"
				Else
					If num < 10 Then
						codigo = "0" & num.ToString()
					Else

						codigo = num.ToString()

					End If
				End If
				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.FrmclasiffierSura.IngresarCodigo' at 10;13.", repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigoInfo, New RecordItemIndex(1))
				repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigo.DoubleClick()
				' repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigo.Click("10;13");
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CodClasificacion' with focus on 'MDIPrincipal.FrmclasiffierSura.IngresarCodigo'.", repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigoInfo, New RecordItemIndex(2))
				repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigo.PressKeys(codigo)
				Delay.Milliseconds(0)

				index += 1
				codigo = String.Empty
			End While

			Report.Info("info", "Se hace click al Botón Aceptar")
			repo.MensajePantalla.Button.Click()
		End Sub

	End Class
End Namespace
