'''////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' Your custom recording code should go in this file.
' The designer will only add methods to this file, so your custom code won't be overwritten.
' http://www.ranorex.com
'
'''////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Repository
Imports Ranorex.Core.Testing

Namespace IQDOC_Sanitas.CargaDatos
	Public Partial Class ValidacionFolder
		''' <summary>
		''' This method gets called right after the recording has been started.
		''' It can be used to execute recording specific initialization code.
		''' </summary>
		Private Sub Init()
			' Your recording specific initialization code goes here.
		End Sub

		Public Sub CargaDatos()
			Dim a As String = repo.FrmDatosImagen.TxtPropiedades.TextValue
			Dim b = a.Split(New String() {"Solicitud_id = ", vbLf & "5."}, StringSplitOptions.RemoveEmptyEntries)
			Dim folderid As String = b(1)

			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDatosImagen.CmdCerrar' at Center.", repo.FrmDatosImagen.CmdCerrarInfo, New RecordItemIndex(1))
			repo.FrmDatosImagen.CmdCerrar.Click()
			Delay.Milliseconds(0)

			If SolicitudID = folderid Then

				'#Region "CargaDatos1"
				Mouse.DefaultMoveTime = 300
				Keyboard.DefaultKeyPressTime = 20
				Delay.SpeedFactor = 1.0

				Init()

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NitIPS' with focus on 'MDIPrincipal.TabMain.TXTNITIPS'.", repo.MDIPrincipal.TabMain.TXTNITIPSInfo, New RecordItemIndex(0))
				repo.MDIPrincipal.TabMain.TXTNITIPS.PressKeys(NitIPS)
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Nfactura' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, New RecordItemIndex(1))
				repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys(Nfactura)
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TXTSUCURSAL' at 19;5.", repo.TXTSUCURSALInfo, New RecordItemIndex(2))
				repo.TXTSUCURSAL.Click("19;5")
				Delay.Milliseconds(0)

				'#End Region

				'#Region "CargaDatos2"

				Try
					Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)" & vbCr & vbLf & "Mouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, New RecordItemIndex(0))
					repo.InformacionRIPS_cof.Aceptar.Click()
					Delay.Milliseconds(0)
				Catch ex As Exception
					Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(0))
				End Try

				'Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.CR254946CONS307CENTROMEDICOSANT'.", repo.List1000.CR254946CONS307CENTROMEDICOSANTInfo, new RecordItemIndex(1));
				'repo.List1000.CR254946CONS307CENTROMEDICOSANT.Select();
				'Delay.Milliseconds(0);

				'Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'MDIPrincipal.TabMain.CerrarSucursalDDL'.", repo.MDIPrincipal.TabMain.CerrarSucursalDDLInfo, new RecordItemIndex(2));
				'repo.MDIPrincipal.TabMain.CerrarSucursalDDL.Press();
				'Delay.Milliseconds(0);

				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.FechaFactura' at Center.", repo.MDIPrincipal.TabMain.FechaFacturaInfo, New RecordItemIndex(3))
				repo.MDIPrincipal.TabMain.FechaFactura.DoubleClick()
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FechaFactura' with focus on 'MDIPrincipal.TabMain.FechaFactura'.", repo.MDIPrincipal.TabMain.FechaFacturaInfo, New RecordItemIndex(4))
				repo.MDIPrincipal.TabMain.FechaFactura.PressKeys(FechaFactura)
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.TextArea2' at Center.", repo.MDIPrincipal.TabMain.TextArea2Info, New RecordItemIndex(5))
				repo.MDIPrincipal.TabMain.TextArea2.DoubleClick()
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Periodo' with focus on 'MDIPrincipal.TabMain.TextArea2'.", repo.MDIPrincipal.TabMain.TextArea2Info, New RecordItemIndex(6))
				repo.MDIPrincipal.TabMain.TextArea2.EnsureVisible()
				Keyboard.Press(Periodo)
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipHonorario' with focus on 'MDIPrincipal.TabMain.TipoHonorarioText'.", repo.MDIPrincipal.TabMain.TipoHonorarioTextInfo, New RecordItemIndex(7))
				repo.MDIPrincipal.TabMain.TipoHonorarioText.PressKeys(TipHonorario)
				Delay.Milliseconds(0)

				'#End Region

				'#Region "CargaDatos3"

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Producto' with focus on 'MDIPrincipal.TabMain.Producto'.", repo.MDIPrincipal.TabMain.ProductoInfo, New RecordItemIndex(0))
				repo.MDIPrincipal.TabMain.Producto.PressKeys(Producto)
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Plan' with focus on 'MDIPrincipal.TabMain.Plan'.", repo.MDIPrincipal.TabMain.PlanInfo, New RecordItemIndex(1))
				repo.MDIPrincipal.TabMain.Plan.PressKeys(Plan)
				Delay.Milliseconds(0)
				'#End Region

				'#Region "CargaDatos4"
				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.ValorBruto' at Center.", repo.MDIPrincipal.TabMain.ValorBrutoInfo, New RecordItemIndex(0))
				repo.MDIPrincipal.TabMain.ValorBruto.DoubleClick()
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValBruto' with focus on 'MDIPrincipal.TabMain.ValorBruto'.", repo.MDIPrincipal.TabMain.ValorBrutoInfo, New RecordItemIndex(1))
				repo.MDIPrincipal.TabMain.ValorBruto.PressKeys(ValBruto)
				Delay.Milliseconds(0)

				'#End Region

				'#Region "CargaDevolucion"
				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F7}' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, New RecordItemIndex(0))
				repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys("{F7}")
				Delay.Milliseconds(0)

				'Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'FrmControllerCapturer.CodigoCausal'.", repo.FrmControllerCapturer.CodigoCausalInfo, new RecordItemIndex(1));
				'repo.FrmControllerCapturer.CodigoCausal.Focus();
				'Delay.Milliseconds(0);

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'FrmControllerCapturer.CodigoCausal'.", repo.FrmControllerCapturer.CodigoCausalInfo, New RecordItemIndex(2))
				repo.FrmControllerCapturer.CodigoCausal.PressKeys(" ")
				Delay.Milliseconds(0)

				'Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.CodigoCausal' at 46;8.", repo.FrmControllerCapturer.CodigoCausalInfo, new RecordItemIndex(3));
				'repo.FrmControllerCapturer.CodigoCausal.Click("46;8");
				'Delay.Milliseconds(0);

				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.Text' at 50;27.", repo.FrmControllerCapturer.TextInfo, New RecordItemIndex(4))
				repo.FrmControllerCapturer.Text.Click("50;27")
				Delay.Milliseconds(0)

				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'devoluciones Prueba' with focus on 'FrmControllerCapturer.Text'.", repo.FrmControllerCapturer.TextInfo, New RecordItemIndex(5))
				repo.FrmControllerCapturer.Text.PressKeys("devoluciones Prueba")
				Delay.Milliseconds(0)

				'Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.Text' at 144;161.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(6));
				'repo.FrmControllerCapturer.Text.Click("144;161");
				'Delay.Milliseconds(0);

				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.BtnSalirCausal' at Center.", repo.FrmControllerCapturer.BtnSalirCausalInfo, New RecordItemIndex(7))
				repo.FrmControllerCapturer.BtnSalirCausal.Click()
				Delay.Milliseconds(0)

				'Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, new RecordItemIndex(8));
				'repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys("{Tab}");
				'Delay.Milliseconds(0);

						'Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, new RecordItemIndex(9));
						'repo.InformacionRIPS_cof.Aceptar.Click();
						'Delay.Milliseconds(0);
				Try
				Catch ex As Exception
					Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(9))

					'#End Region

					'				#region CargaDatosFinalSinRPS
					'				try {
					'                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, new RecordItemIndex(0));
					'                repo.InformacionRIPS_cof.Aceptar.Click();
					'                Delay.Milliseconds(0);
					'            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
					'            
					'            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.CmdSave' at 49;5.", repo.MDIPrincipal.CmdSaveInfo, new RecordItemIndex(1));
					'            repo.MDIPrincipal.CmdSave.Click("49;5");
					'            Delay.Milliseconds(0);
					'            
					'            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamposOmitidos.ButtonSi' at Center.", repo.CamposOmitidos.ButtonSiInfo, new RecordItemIndex(2));
					'            repo.CamposOmitidos.ButtonSi.Click();
					'            Delay.Milliseconds(0);

					'				#endregion
					'				
					'				#region AceptarDevoluciones
					'				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamposOmitidos.ButtonSi' at Center.", repo.CamposOmitidos.ButtonSiInfo, new RecordItemIndex(0));
					'            repo.CamposOmitidos.ButtonSi.Click();
					'            Delay.Milliseconds(0);
					'				#endregion
				End Try
			End If
		End Sub



	End Class

	Public Partial Class Recorrido
		Private h As String
	End Class

End Namespace
