'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace IQDOC_Sanitas.CargaDatos
    ''' <summary>
    '''The Validacion recording.
    ''' </summary>
    <TestModule("75df2d03-1e31-46db-b926-98ca115ccaf2", ModuleType.Recording, 1)> _
    Partial Public Class Validacion
        Implements ITestModule
    
        ''' <summary>
        ''' Holds an instance of the Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        ''' </summary>
        Public Shared repo as Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository = Global.IQDOC_Sanitas.IQDOC_Sanitas.IQDOC_SanitasRepository.Instance
    
        Shared _instance as Validacion = new Validacion()
    
        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub
    
        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As Validacion
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
            <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub
    
        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", Global.Ranorex.Core.Constants.CodeGenVersion)> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 20
            Delay.SpeedFactor = 1.00
    
            Init()
    
            Try
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'FacturacionElectronica_cof.Aceptar' at Center.", repo.FacturacionElectronica_cof.AceptarInfo, new RecordItemIndex(0))
                repo.FacturacionElectronica_cof.Aceptar.Click()
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(0))
            End Try
    
            Try
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'FrmControllerCapturer.ActiveCheck' at Center.", repo.FrmControllerCapturer.ActiveCheckInfo, new RecordItemIndex(1))
                repo.FrmControllerCapturer.ActiveCheck.Click()
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(1))
            End Try
    
            Try
                Report.Log(ReportLevel.Info, "Keyboard", "(Optional Action)"+Chr(13)+""+Chr(10)+"Key sequence 'Prueba Observación RANOREX' with focus on 'FrmControllerCapturer.Text'.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(2))
                repo.FrmControllerCapturer.Text.PressKeys("Prueba Observación RANOREX")
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(2))
            End Try
    
            Try
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'FrmControllerCapturer.BtnSalirCausal' at Center.", repo.FrmControllerCapturer.BtnSalirCausalInfo, new RecordItemIndex(3))
                repo.FrmControllerCapturer.BtnSalirCausal.Click()
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(3))
            End Try
    
            Try
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'MDIPrincipal.Copy_of_CmdSave' at Center.", repo.MDIPrincipal.Copy_of_CmdSaveInfo, new RecordItemIndex(4))
                repo.MDIPrincipal.Copy_of_CmdSave.Click()
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(4))
            End Try
    
            Try
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)"+Chr(13)+""+Chr(10)+"Mouse Left Click item 'CamposOmitidos.ButtonSi' at Center.", repo.CamposOmitidos.ButtonSiInfo, new RecordItemIndex(5))
                repo.CamposOmitidos.ButtonSi.Click()
                Delay.Milliseconds(0)
            Catch ex As Exception
                Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " & ex.Message, New RecordItemIndex(5))
            End Try
    
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
