///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace IQDOC_Sanitas.CargaDatos
{
    public partial class AbrirVentanaInfo
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ObtenerSolicitudId()
        {
            
			string a=repo.FrmDatosImagen.TxtPropiedades.TextValue;
			var b=a.Split(new string [] {"Solicitud_id = ","\n5."} ,StringSplitOptions.RemoveEmptyEntries);
			string folderiditem=b[1];
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDatosImagen.CmdCerrar' at Center.", repo.FrmDatosImagen.CmdCerrarInfo, new RecordItemIndex(1));
			repo.FrmDatosImagen.CmdCerrar.Click();
			Delay.Milliseconds(0);
			
			FolderId=folderiditem;
        }

    }
}
