///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IQDOC_Sanitas.CargaDatos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CapturaEncabezadoDevoluciones recording.
    /// </summary>
    [TestModule("254bd34c-3252-41ae-9913-2d1751744911", ModuleType.Recording, 1)]
    public partial class CapturaEncabezadoDevoluciones : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        /// </summary>
        public static global::IQDOC_Sanitas.IQDOC_SanitasRepository repo = global::IQDOC_Sanitas.IQDOC_SanitasRepository.Instance;

        static CapturaEncabezadoDevoluciones instance = new CapturaEncabezadoDevoluciones();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CapturaEncabezadoDevoluciones()
        {
            NitIPS = "842000144 - ESE UBA NUESTRA SEÑORA DEL CARMEN";
            NFactura = "12345";
            Sucursal = "AV ORINOCO CALLE 10   CUMARIBO";
            Periodo = "11232020";
            TipHonorario = "AB -- AMBULANCIA";
            Producto = "PAC";
            Plan = "Plan Empresarial";
            ValBruto = "10000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CapturaEncabezadoDevoluciones Instance
        {
            get { return instance; }
        }

#region Variables

        string _Periodo;

        /// <summary>
        /// Gets or sets the value of variable Periodo.
        /// </summary>
        [TestVariable("8565e743-6466-42c7-8728-3715914ffe99")]
        public string Periodo
        {
            get { return _Periodo; }
            set { _Periodo = value; }
        }

        string _TipHonorario;

        /// <summary>
        /// Gets or sets the value of variable TipHonorario.
        /// </summary>
        [TestVariable("8aa84e1d-9032-4958-ba32-8737fb010ea9")]
        public string TipHonorario
        {
            get { return _TipHonorario; }
            set { _TipHonorario = value; }
        }

        string _ValBruto;

        /// <summary>
        /// Gets or sets the value of variable ValBruto.
        /// </summary>
        [TestVariable("62ff3be4-5e59-491a-b696-89fdf9106d62")]
        public string ValBruto
        {
            get { return _ValBruto; }
            set { _ValBruto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NitIPS.
        /// </summary>
        [TestVariable("d160ba4b-4826-47d0-8532-2f3155145538")]
        public string NitIPS
        {
            get { return repo.NitIPS; }
            set { repo.NitIPS = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Sucursal.
        /// </summary>
        [TestVariable("4087a140-ebe0-4ffa-b3d1-70cba6332c2f")]
        public string Sucursal
        {
            get { return repo.Sucursal; }
            set { repo.Sucursal = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NFactura.
        /// </summary>
        [TestVariable("166a2ebb-2665-4589-b35f-c7400fd484c0")]
        public string NFactura
        {
            get { return repo.Nfactura; }
            set { repo.Nfactura = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Producto.
        /// </summary>
        [TestVariable("db7149e5-88a0-4c59-9c78-f5ecab7d8af9")]
        public string Producto
        {
            get { return repo.Producto; }
            set { repo.Producto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Plan.
        /// </summary>
        [TestVariable("26fdc1c5-1976-4cff-959a-20771dad19be")]
        public string Plan
        {
            get { return repo.Plan; }
            set { repo.Plan = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.CmdStart' at 95;10.", repo.MDIPrincipal.CmdStartInfo, new RecordItemIndex(0));
            //repo.MDIPrincipal.CmdStart.Click("95;10");
            //Delay.Milliseconds(0);
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'FrmPOPUp_cof.Btn_CerrarVentana' at Center.", repo.FrmPOPUp_cof.Btn_CerrarVentanaInfo, new RecordItemIndex(1));
                //repo.FrmPOPUp_cof.Btn_CerrarVentana.Click();
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NitIPS' with focus on 'MDIPrincipal.TabMain.TXTNITIPS'.", repo.MDIPrincipal.TabMain.TXTNITIPSInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.TabMain.TXTNITIPS.PressKeys(NitIPS);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.TabMain.DDLNITIPS' at 11;10.", repo.MDIPrincipal.TabMain.DDLNITIPSInfo, new RecordItemIndex(3));
            //repo.MDIPrincipal.TabMain.DDLNITIPS.Click("11;10");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItem10263507ARBOLEDANARANJOLUIS' at 160;4.", repo.List1000.ListItem10263507ARBOLEDANARANJOLUISInfo, new RecordItemIndex(4));
            //repo.List1000.ListItem10263507ARBOLEDANARANJOLUIS.Click("160;4");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.TXTNUMEROFACTURA' at Center.", repo.MDIPrincipal.TabMain.TXTNUMEROFACTURAInfo, new RecordItemIndex(5));
            repo.MDIPrincipal.TabMain.TXTNUMEROFACTURA.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NFactura' with focus on 'MDIPrincipal.TabMain.TXTNUMEROFACTURA'.", repo.MDIPrincipal.TabMain.TXTNUMEROFACTURAInfo, new RecordItemIndex(6));
            repo.MDIPrincipal.TabMain.TXTNUMEROFACTURA.PressKeys(NFactura);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.TabMain.AbrirSucursalDDL' at 6;8.", repo.MDIPrincipal.TabMain.AbrirSucursalDDLInfo, new RecordItemIndex(7));
            repo.MDIPrincipal.TabMain.AbrirSucursalDDL.Click("6;8");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, new RecordItemIndex(8));
                repo.InformacionRIPS_cof.Aceptar.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(8)); }
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.TabMain.AbrirSucursalDDL' at 6;8.", repo.MDIPrincipal.TabMain.AbrirSucursalDDLInfo, new RecordItemIndex(9));
            //repo.MDIPrincipal.TabMain.AbrirSucursalDDL.Click("6;8");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.CR254946CONS307CENTROMEDICOSANT'.", repo.List1000.CR254946CONS307CENTROMEDICOSANTInfo, new RecordItemIndex(10));
            repo.List1000.CR254946CONS307CENTROMEDICOSANT.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'MDIPrincipal.TabMain.CerrarSucursalDDL'.", repo.MDIPrincipal.TabMain.CerrarSucursalDDLInfo, new RecordItemIndex(11));
            repo.MDIPrincipal.TabMain.CerrarSucursalDDL.Press();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.CR254946CONS307CENTROMEDICOSANT' at Center.", repo.List1000.CR254946CONS307CENTROMEDICOSANTInfo, new RecordItemIndex(12));
            //repo.List1000.CR254946CONS307CENTROMEDICOSANT.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Sucursal' with focus on 'TXTSUCURSAL'.", repo.TXTSUCURSALInfo, new RecordItemIndex(13));
            //repo.TXTSUCURSAL.PressKeys(Sucursal);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.Periodo' at Center.", repo.MDIPrincipal.TabMain.PeriodoInfo, new RecordItemIndex(14));
            repo.MDIPrincipal.TabMain.Periodo.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Periodo'.", new RecordItemIndex(15));
            Keyboard.Press(Periodo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TipHonorario' with focus on 'MDIPrincipal.TabMain.TipoHonorarioText'.", repo.MDIPrincipal.TabMain.TipoHonorarioTextInfo, new RecordItemIndex(16));
            repo.MDIPrincipal.TabMain.TipoHonorarioText.PressKeys(TipHonorario);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Producto' with focus on 'MDIPrincipal.TabMain.Producto'.", repo.MDIPrincipal.TabMain.ProductoInfo, new RecordItemIndex(17));
            repo.MDIPrincipal.TabMain.Producto.PressKeys(Producto);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Plan' with focus on 'MDIPrincipal.TabMain.Plan'.", repo.MDIPrincipal.TabMain.PlanInfo, new RecordItemIndex(18));
            repo.MDIPrincipal.TabMain.Plan.PressKeys(Plan);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'MDIPrincipal.TabMain.ValorBruto' at Center.", repo.MDIPrincipal.TabMain.ValorBrutoInfo, new RecordItemIndex(19));
            repo.MDIPrincipal.TabMain.ValorBruto.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ValBruto' with focus on 'MDIPrincipal.TabMain.ValorBruto'.", repo.MDIPrincipal.TabMain.ValorBrutoInfo, new RecordItemIndex(20));
            repo.MDIPrincipal.TabMain.ValorBruto.PressKeys(ValBruto);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to not exist. Associated repository item: 'ControlDeValidacionDeCampos'", repo.ControlDeValidacionDeCampos.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(21));
            //repo.ControlDeValidacionDeCampos.SelfInfo.WaitForNotExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.TabMain.NumeroFactura' at 49;9.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, new RecordItemIndex(22));
            repo.MDIPrincipal.TabMain.NumeroFactura.Click("49;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{F7}' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, new RecordItemIndex(23));
            repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys("{F7}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.ActiveCheck' at 46;8.", repo.FrmControllerCapturer.ActiveCheckInfo, new RecordItemIndex(24));
            repo.FrmControllerCapturer.ActiveCheck.Click("46;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.Text' at 50;27.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(25));
            repo.FrmControllerCapturer.Text.Click("50;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'devoluciones Prueba' with focus on 'FrmControllerCapturer.Text'.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(26));
            repo.FrmControllerCapturer.Text.PressKeys("devoluciones Prueba");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmControllerCapturer.Text' at 144;161.", repo.FrmControllerCapturer.TextInfo, new RecordItemIndex(27));
            repo.FrmControllerCapturer.Text.Click("144;161");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'MDIPrincipal.TabMain.NumeroFactura'.", repo.MDIPrincipal.TabMain.NumeroFacturaInfo, new RecordItemIndex(28));
            repo.MDIPrincipal.TabMain.NumeroFactura.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'InformacionRIPS_cof.Aceptar' at Center.", repo.InformacionRIPS_cof.AceptarInfo, new RecordItemIndex(29));
            repo.InformacionRIPS_cof.Aceptar.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AuxiliarDeAuditoriaMedica.FadeModalNgIsolateScope' at 825;436.", repo.AuxiliarDeAuditoriaMedica.FadeModalNgIsolateScopeInfo, new RecordItemIndex(30));
            //repo.AuxiliarDeAuditoriaMedica.FadeModalNgIsolateScope.Click("825;436");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.CmdSave' at Center.", repo.MDIPrincipal.CmdSaveInfo, new RecordItemIndex(31));
            repo.MDIPrincipal.CmdSave.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CamposOmitidos.ButtonSi' at Center.", repo.CamposOmitidos.ButtonSiInfo, new RecordItemIndex(32));
            repo.CamposOmitidos.ButtonSi.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPOPUp_cof.Btn_CerrarVentana' at Center.", repo.FrmPOPUp_cof.Btn_CerrarVentanaInfo, new RecordItemIndex(33));
            //repo.FrmPOPUp_cof.Btn_CerrarVentana.Click();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
