///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace IQDOC_Sanitas.CargaDatos
{
	public partial class Clasificacion
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void Clasificar()
		{
			// TODO: Replace the following line with your code implementation.
			//   throw new NotImplementedException();
//			string folderid=ParFolderId;
//
//			if (SolicitudId==folderid){
			
			int index=0;
			String codigo=string.Empty;
			Random rnd = new Random();
			
			
			while (!repo.MensajePantalla.FinDocumentoInfo.Exists(2000))
				
			{
				try {
					Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'MensajePantalla.Button' at Center.", repo.MensajePantalla.ButtonInfo, new RecordItemIndex(3));
					repo.MensajePantalla.Button.Click();
					Delay.Milliseconds(0);
				} catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
				
				int num = rnd.Next(1,44);
				//WinForms.MessageBox.Show(num.ToString());
				if (index==0)
				{
					codigo="00";
				}
				else
				{
					if (num<10)
					{
						codigo="0"+num.ToString();
					}
					
					else{
						codigo=num.ToString();
					}
					
				}
				
				
				
				Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.FrmclasiffierSura.IngresarCodigo' at 10;13.", repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigoInfo, new RecordItemIndex(1));
				repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigo.DoubleClick();
				// repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigo.Click("10;13");
				Delay.Milliseconds(0);
				
				Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CodClasificacion' with focus on 'MDIPrincipal.FrmclasiffierSura.IngresarCodigo'.", repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigoInfo, new RecordItemIndex(2));
				repo.MDIPrincipal.FrmclasiffierSura.IngresarCodigo.PressKeys(codigo);
				Delay.Milliseconds(0);
				
				index++;
				codigo=string.Empty;
				
				
				
			}
			
			Report.Info("info","Se hace click al Botón Aceptar");
			repo.MensajePantalla.Button.Click();
			
			     Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.Copy_of_Btn_GuadarClasi' at Center.", repo.MDIPrincipal.Copy_of_Btn_GuadarClasiInfo, new RecordItemIndex(1));
            repo.MDIPrincipal.Copy_of_Btn_GuadarClasi.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MDIPrincipal.FrmclasiffierSura.Btn_Salir' at Center.", repo.MDIPrincipal.FrmclasiffierSura.Btn_SalirInfo, new RecordItemIndex(2));
            repo.MDIPrincipal.FrmclasiffierSura.Btn_Salir.Click();
            Delay.Milliseconds(0);
//			}
		}

	}
}
