///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IQDOC_Sanitas.CargaDatos
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidacionFolder recording.
    /// </summary>
    [TestModule("1de422d3-6c34-4bb9-86fb-80de3ace7aa3", ModuleType.Recording, 1)]
    public partial class ValidacionFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        /// </summary>
        public static global::IQDOC_Sanitas.IQDOC_SanitasRepository repo = global::IQDOC_Sanitas.IQDOC_SanitasRepository.Instance;

        static ValidacionFolder instance = new ValidacionFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidacionFolder()
        {
            SolicitudID = "DCC8CE34-0E86-4BB4-BCB5-B84F4679941C";
            NitIPS = "";
            Nfactura = "";
            FechaFactura = "";
            Periodo = "";
            TipHonorario = "";
            Producto = "";
            Plan = "";
            ValBruto = "";
            NFacturaOriginal = "";
            ParFolderId = "";
            TipoNoPbs = "";
            CBOProducto = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidacionFolder Instance
        {
            get { return instance; }
        }

#region Variables

        string _SolicitudID;

        /// <summary>
        /// Gets or sets the value of variable SolicitudID.
        /// </summary>
        [TestVariable("478bfbc6-408f-470a-a323-609874a6d8f0")]
        public string SolicitudID
        {
            get { return _SolicitudID; }
            set { _SolicitudID = value; }
        }

        string _FechaFactura;

        /// <summary>
        /// Gets or sets the value of variable FechaFactura.
        /// </summary>
        [TestVariable("30ff0f56-640d-4404-83d8-7e40964d179a")]
        public string FechaFactura
        {
            get { return _FechaFactura; }
            set { _FechaFactura = value; }
        }

        string _Periodo;

        /// <summary>
        /// Gets or sets the value of variable Periodo.
        /// </summary>
        [TestVariable("77110777-b1c5-4678-98ee-d141f8c304ff")]
        public string Periodo
        {
            get { return _Periodo; }
            set { _Periodo = value; }
        }

        string _TipHonorario;

        /// <summary>
        /// Gets or sets the value of variable TipHonorario.
        /// </summary>
        [TestVariable("5b5b5b45-de4a-4983-bf46-5f4d2c10d871")]
        public string TipHonorario
        {
            get { return _TipHonorario; }
            set { _TipHonorario = value; }
        }

        string _ValBruto;

        /// <summary>
        /// Gets or sets the value of variable ValBruto.
        /// </summary>
        [TestVariable("59eede5d-6fda-451a-9cc7-01c79a040477")]
        public string ValBruto
        {
            get { return _ValBruto; }
            set { _ValBruto = value; }
        }

        string _NFacturaOriginal;

        /// <summary>
        /// Gets or sets the value of variable NFacturaOriginal.
        /// </summary>
        [TestVariable("1cb6f052-de6e-4f24-8813-0523927d4244")]
        public string NFacturaOriginal
        {
            get { return _NFacturaOriginal; }
            set { _NFacturaOriginal = value; }
        }

        string _ParFolderId;

        /// <summary>
        /// Gets or sets the value of variable ParFolderId.
        /// </summary>
        [TestVariable("7dbad027-2d8d-4446-aece-e29e376e2259")]
        public string ParFolderId
        {
            get { return _ParFolderId; }
            set { _ParFolderId = value; }
        }

        string _TipoNoPbs;

        /// <summary>
        /// Gets or sets the value of variable TipoNoPbs.
        /// </summary>
        [TestVariable("9699049f-17bb-454d-8b7e-01c2f33c6f90")]
        public string TipoNoPbs
        {
            get { return _TipoNoPbs; }
            set { _TipoNoPbs = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CodCausal.
        /// </summary>
        [TestVariable("76573065-3087-4296-9bf6-8692000dcf32")]
        public string CodCausal
        {
            get { return repo.CodCausal; }
            set { repo.CodCausal = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NitIPS.
        /// </summary>
        [TestVariable("0b89e05f-a20b-4c31-9389-ce5ed05e7195")]
        public string NitIPS
        {
            get { return repo.NitIPS; }
            set { repo.NitIPS = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Nfactura.
        /// </summary>
        [TestVariable("3d5a2773-8f34-4b7e-9f25-92a4b0c7a1db")]
        public string Nfactura
        {
            get { return repo.Nfactura; }
            set { repo.Nfactura = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Producto.
        /// </summary>
        [TestVariable("bf45e292-c442-4798-af56-d4730aee2f2a")]
        public string Producto
        {
            get { return repo.Producto; }
            set { repo.Producto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Plan.
        /// </summary>
        [TestVariable("8a359ef7-2afa-484c-bbb2-9e74de34fd09")]
        public string Plan
        {
            get { return repo.Plan; }
            set { repo.Plan = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CBOProducto.
        /// </summary>
        [TestVariable("4da9608c-7426-432a-b6ca-2e301e030daf")]
        public string CBOProducto
        {
            get { return repo.CBOProducto; }
            set { repo.CBOProducto = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CargaDatos();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
