///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IQDOC_Sanitas.ScriptGeneral
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValFolder recording.
    /// </summary>
    [TestModule("0595008d-0d95-4719-85d1-a9d5a98fc032", ModuleType.Recording, 1)]
    public partial class ValFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::IQDOC_Sanitas.IQDOC_SanitasRepository repository.
        /// </summary>
        public static global::IQDOC_Sanitas.IQDOC_SanitasRepository repo = global::IQDOC_Sanitas.IQDOC_SanitasRepository.Instance;

        static ValFolder instance = new ValFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValFolder()
        {
            SolicitudID = "";
            FechaFactura = "";
            Periodo = "";
            TipHonorario = "";
            ValBruto = "";
            ParFolderId = "";
            NFacturaOriginal = "";
            Prefijo = "";
            NitIPS = "";
            Nfactura = "";
            Producto = "";
            Plan = "";
            CBOProducto = "";
            TipoNoPbs = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValFolder Instance
        {
            get { return instance; }
        }

#region Variables

        string _SolicitudID;

        /// <summary>
        /// Gets or sets the value of variable SolicitudID.
        /// </summary>
        [TestVariable("eebec97c-0a0b-4afd-affd-1cb20a4b34ef")]
        public string SolicitudID
        {
            get { return _SolicitudID; }
            set { _SolicitudID = value; }
        }

        string _FechaFactura;

        /// <summary>
        /// Gets or sets the value of variable FechaFactura.
        /// </summary>
        [TestVariable("bf08318f-3e7a-44fb-9529-106a1d7c7d7e")]
        public string FechaFactura
        {
            get { return _FechaFactura; }
            set { _FechaFactura = value; }
        }

        string _Periodo;

        /// <summary>
        /// Gets or sets the value of variable Periodo.
        /// </summary>
        [TestVariable("9a49b6f5-1b31-4e1b-95dd-62af4a447c41")]
        public string Periodo
        {
            get { return _Periodo; }
            set { _Periodo = value; }
        }

        string _TipHonorario;

        /// <summary>
        /// Gets or sets the value of variable TipHonorario.
        /// </summary>
        [TestVariable("b2b146ef-51b1-4e7d-8ab6-66cca74b2615")]
        public string TipHonorario
        {
            get { return _TipHonorario; }
            set { _TipHonorario = value; }
        }

        string _ValBruto;

        /// <summary>
        /// Gets or sets the value of variable ValBruto.
        /// </summary>
        [TestVariable("e7c4be06-7dde-4029-bbf8-332aaa2ccac7")]
        public string ValBruto
        {
            get { return _ValBruto; }
            set { _ValBruto = value; }
        }

        string _ParFolderId;

        /// <summary>
        /// Gets or sets the value of variable ParFolderId.
        /// </summary>
        [TestVariable("f76d6598-7f37-4db2-8a4a-19c2d1e48edd")]
        public string ParFolderId
        {
            get { return _ParFolderId; }
            set { _ParFolderId = value; }
        }

        string _NFacturaOriginal;

        /// <summary>
        /// Gets or sets the value of variable NFacturaOriginal.
        /// </summary>
        [TestVariable("4f82039f-5643-4af7-99c1-3610ec0bdfa2")]
        public string NFacturaOriginal
        {
            get { return _NFacturaOriginal; }
            set { _NFacturaOriginal = value; }
        }

        string _Prefijo;

        /// <summary>
        /// Gets or sets the value of variable Prefijo.
        /// </summary>
        [TestVariable("cf8ae2b8-a2fb-4409-a56b-0ef3c04c255a")]
        public string Prefijo
        {
            get { return _Prefijo; }
            set { _Prefijo = value; }
        }

        string _TipoNoPbs;

        /// <summary>
        /// Gets or sets the value of variable TipoNoPbs.
        /// </summary>
        [TestVariable("8cb2ad93-8103-463b-acac-efd1bd016917")]
        public string TipoNoPbs
        {
            get { return _TipoNoPbs; }
            set { _TipoNoPbs = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable NitIPS.
        /// </summary>
        [TestVariable("1fab2f2b-09cc-403a-887b-e31045c33ab6")]
        public string NitIPS
        {
            get { return repo.NitIPS; }
            set { repo.NitIPS = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Nfactura.
        /// </summary>
        [TestVariable("85f8a6df-6e98-4e48-a57f-d333548e0584")]
        public string Nfactura
        {
            get { return repo.Nfactura; }
            set { repo.Nfactura = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Producto.
        /// </summary>
        [TestVariable("33523908-409a-4b87-acf8-ee6f3bb9f026")]
        public string Producto
        {
            get { return repo.Producto; }
            set { repo.Producto = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Plan.
        /// </summary>
        [TestVariable("f0ea21f0-8817-4a87-8859-a72b96b7210a")]
        public string Plan
        {
            get { return repo.Plan; }
            set { repo.Plan = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable CBOProducto.
        /// </summary>
        [TestVariable("3b8fc16b-fde5-4670-85b9-3742cde8d3e9")]
        public string CBOProducto
        {
            get { return repo.CBOProducto; }
            set { repo.CBOProducto = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            ValidacionCargaDatos();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
